#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = Symfony\Component\Console\Input\ArgvInput::create(),
    Symfony\Component\Console\Output\ConsoleOutput::create()
);

$kernel->terminate($input, $status);

exit($status);
